[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
node_registry = "GLpPpGCANeD7mLuY7XdJ2mAXX7MSLEdaLr91MMjoscno"

[programs.localnet]
node_registry = "GLpPpGCANeD7mLuY7XdJ2mAXX7MSLEdaLr91MMjoscno"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
